# Generated by Django 4.1.7 on 2023-02-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
